# Generated by Django 3.2 on 2023-05-19 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('news_type', models.IntegerField(choices=[(1, 'General'), (2, 'Systems'), (3, 'Discoveries')], default=1)),
                ('news_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('news_content', models.TextField(default='Add content here', max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_on', 'publish_date'],
            },
        ),
    ]
