# Generated by Django 3.2 on 2023-05-19 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['updated_on', 'publish_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='unknown-content', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
