# Generated by Django 3.2 on 2023-05-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(default='Add content here', max_length=4000),
        ),
    ]
