# Generated by Django 3.2 on 2023-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='approved_post',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Displayed')], default=0),
        ),
    ]
