# Generated by Django 3.2 on 2023-05-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['rank', 'name'], 'verbose_name_plural': 'Personnel'},
        ),
    ]
