# Generated by Django 3.2 on 2023-05-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personnel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
