# Generated by Django 3.2 on 2023-05-09 22:22

from django.db import migrations, models
import personnel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0003_delete_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(default=personnel.models.unique_member_id, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('originated_from', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField(choices=[(1, 'Rookie'), (2, 'Soldier'), (3, 'Veteran'), (4, 'Commander')], default=1)),
                ('speciality', models.TextField(default='', max_length=1000)),
                ('current_status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Leave'), (3, 'Medical Leave'), (4, 'Retired'), (5, 'Deceased')], default=1)),
                ('joined', models.DateField(auto_now=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Personnel',
                'ordering': ['rank', 'name'],
            },
        ),
    ]
