# Generated by Django 3.2 on 2023-05-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='member_id',
        ),
    ]
