# Generated by Django 3.2 on 2023-05-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_alter_personnel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['-rank', 'current_status', 'name'], 'verbose_name_plural': 'Personnel'},
        ),
    ]
