# Generated by Django 3.2 on 2023-06-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_personnel_authorised'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['-joined'], 'verbose_name_plural': 'Personnel'},
        ),
    ]
