# Generated by Django 3.2 on 2023-06-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_alter_personnel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
