# Generated by Django 3.2 on 2023-05-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0007_alter_personnel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=100, unique=True)),
                ('mission_grade', models.IntegerField(choices=[(1, 'Extreme'), (2, 'Dangerous'), (3, 'Serious'), (4, 'Moderate'), (5, 'Basic'), (6, 'Training')], default=5)),
                ('description', models.TextField(max_length=2000)),
                ('prep_time', models.PositiveIntegerField(default=5)),
                ('mission_length', models.PositiveIntegerField(default=1)),
                ('mission_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
            ],
            options={
                'ordering': ['mission_grade'],
            },
        ),
    ]
