# Generated by Django 3.2 on 2023-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='img_url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
