# Generated by Django 3.2 on 2023-05-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20230524_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['mission_grade', 'mission_length']},
        ),
    ]
