# Generated by Django 3.2 on 2023-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_mission_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='img_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
