# Generated by Django 3.2 on 2023-05-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_mission_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='approved_mission',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Displayed')], default=0),
        ),
    ]
