# Generated by Django 3.2 on 2023-06-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_mission_approved_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={},
        ),
    ]
