# Generated by Django 3.2 on 2023-06-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_mission_approved_mission'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(condition=models.Q(rank='Veteren'), fields=('mission_lead',), name='limit_rank_Veteren_Commander'),
        ),
    ]
