# Generated by Django 3.2 on 2023-06-19 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0007_alter_mission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='', max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_update', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Displayed')], default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update', to='missions.mission')),
                ('name', models.ForeignKey(blank=True, default='Anonymous', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
