# Generated by Django 3.2 on 2023-06-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_alter_mission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField(default='', max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.PositiveIntegerField(choices=[(0, 'Hidden'), (1, 'Displayed')], default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
            ],
        ),
    ]
