# Generated by Django 3.2 on 2023-06-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_remove_mission_limit_rank_veteren_commander'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(condition=models.Q(approved_mission=0), fields=('mission_lead',), name='limit_rank_Veteren_Commander'),
        ),
    ]
