# Generated by Django 3.2 on 2023-06-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='missions.mission'),
        ),
    ]
