# Generated by Django 3.2 on 2023-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0010_remove_update_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
