# Generated by Django 3.2 on 2023-06-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0011_update_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-mission']},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-created_on']},
        ),
    ]
