# Generated by Django 3.2 on 2023-06-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_auto_20230620_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['mission', 'created_on']},
        ),
    ]
