# Generated by Django 3.2 on 2023-07-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0013_alter_update_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['mission']},
        ),
    ]
