# Generated by Django 3.2 on 2023-07-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_alter_personnel_joined'),
        ('missions', '0014_alter_mission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='personnel.personnel'),
        ),
    ]
