# Generated by Django 3.2 on 2023-07-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.PositiveIntegerField(choices=[(0, 'Mineral'), (1, 'Food'), (2, 'Material'), (3, 'Fabric')], default=0)),
                ('approved_item', models.PositiveIntegerField(choices=[(0, 'Hidden'), (1, 'Displayed')], default=0)),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
