# Generated by Django 3.2 on 2023-07-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_category_friendly_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
